import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Search from "@/components/Search";
import Category from "@/components/Category";
import Type from "@/components/Type";
import Order from "@/components/Order";
import CounterProvider, { CounterContext } from "@/context/CounterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CounterProvider>
          <div>
            <Search />
            {/* <Category />
            <Type />
            <Order /> */}
            {children}
          </div>
        </CounterProvider>
      </body>
    </html>
  );
}
